configMapGenerator:
- files:
  - application.yml
  name: t82107479-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: ceappacr.azurecr.io/82107479
  newTag: "202410210646"
